# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Canvacli < Formula
  desc "Agent-first CLI for the Canva Connect API"
  homepage "https://github.com/catalinlongevai/canvacli"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/catalinlongevai/canvacli/releases/download/v1.1.0/canvacli_1.1.0_darwin_amd64.tar.gz"
      sha256 "6208f59d401ed51dacd1a316e4c52468ea696c1fe7c4422b256b75df7031f618"

      define_method(:install) do
        bin.install "canva"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/catalinlongevai/canvacli/releases/download/v1.1.0/canvacli_1.1.0_darwin_arm64.tar.gz"
      sha256 "0db0b8f7738d21ba33532fc0544fefb0aba481989d8665db7ed18f1f55ca217f"

      define_method(:install) do
        bin.install "canva"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/catalinlongevai/canvacli/releases/download/v1.1.0/canvacli_1.1.0_linux_amd64.tar.gz"
      sha256 "c9278adc9ad81e97014b1443c06d6c2c56a56b20612548d078231e435f9d3b25"
      define_method(:install) do
        bin.install "canva"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/catalinlongevai/canvacli/releases/download/v1.1.0/canvacli_1.1.0_linux_arm64.tar.gz"
      sha256 "b1bcebeb9bc577c22d33d07472c50a1089a258408972df996ba3fda07cb5c0b1"
      define_method(:install) do
        bin.install "canva"
      end
    end
  end

  test do
    system "#{bin}/canva --version"
  end
end
