# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Canvacli < Formula
  desc "Agent-first CLI for the Canva Connect API"
  homepage "https://github.com/catalinlongevai/canvacli"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/catalinlongevai/canvacli/releases/download/v2.0.0/canvacli_2.0.0_darwin_amd64.tar.gz"
      sha256 "6268abbdf0fe645c2505d65ab6117e1abc82f9dd63d1bd45086c95ff9873714e"

      define_method(:install) do
        bin.install "canva"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/catalinlongevai/canvacli/releases/download/v2.0.0/canvacli_2.0.0_darwin_arm64.tar.gz"
      sha256 "6c56347f5ac012390945a1c9e349d1e5f049d7a585f4c5155781f7bc0a2e45fa"

      define_method(:install) do
        bin.install "canva"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/catalinlongevai/canvacli/releases/download/v2.0.0/canvacli_2.0.0_linux_amd64.tar.gz"
      sha256 "525f7f925f90e8f15d9403e5e4270ce3832214714991582b601b12cb55073112"
      define_method(:install) do
        bin.install "canva"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/catalinlongevai/canvacli/releases/download/v2.0.0/canvacli_2.0.0_linux_arm64.tar.gz"
      sha256 "af0594002741d62609729bc6528346e385d7b20c54bbefb153fb3fa877150209"
      define_method(:install) do
        bin.install "canva"
      end
    end
  end

  test do
    system "#{bin}/canva --version"
  end
end
