# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Canvacli < Formula
  desc "Agent-first CLI for the Canva Connect API"
  homepage "https://github.com/catalinlongevai/canvacli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/catalinlongevai/canvacli/releases/download/v1.0.0/canvacli_1.0.0_darwin_amd64.tar.gz"
      sha256 "63a9911c0499d541c695644152a734d5f33b6ab4bf04eabd71bb0542a170f6af"

      define_method(:install) do
        bin.install "canva"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/catalinlongevai/canvacli/releases/download/v1.0.0/canvacli_1.0.0_darwin_arm64.tar.gz"
      sha256 "d96de43cb60f018dbd9fce4cf17d32b03983836110d62c356398e78f67ce6308"

      define_method(:install) do
        bin.install "canva"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/catalinlongevai/canvacli/releases/download/v1.0.0/canvacli_1.0.0_linux_amd64.tar.gz"
      sha256 "6324ad6bb6a42d074ca5471f22aef2b266a8bca4f6d0ec35b4427d14db19a394"
      define_method(:install) do
        bin.install "canva"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/catalinlongevai/canvacli/releases/download/v1.0.0/canvacli_1.0.0_linux_arm64.tar.gz"
      sha256 "554b995c27b88a8fd04438fd854aa887050940ad9a19344cf02ef3da143e1e50"
      define_method(:install) do
        bin.install "canva"
      end
    end
  end

  test do
    system "#{bin}/canva --version"
  end
end
